# Generated by Django 3.0.7 on 2020-08-26 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=60)),
                ('subject', models.CharField(blank=True, default='', max_length=60)),
                ('email', models.EmailField(blank=True, default='', max_length=250)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.TextField(blank=True, default='')),
                ('is_email_answer_send', models.BooleanField(default=False)),
                ('notice', models.TextField(blank=True, default='')),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
