# Generated by Django 3.0.7 on 2020-07-27 21:42

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_auto_20200707_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Without title.', max_length=250)),
                ('text', models.TextField(default='')),
                ('image', models.ImageField(upload_to='blog_image/%Y/%m/%d', verbose_name='Главное изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=list, max_length=30), size=None)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='profiles.Profile')),
            ],
        ),
    ]
