# Generated by Django 3.0.7 on 2020-07-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='text_slug',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
